# vim:set ft=sh
MODULES=()

BINARIES=(btrfs)

FILES=()

#HOOKS=(base systemd sd-vconsole plymouth? autodetect microcode modconf kms keyboard block filesystems sd-kmonad sd-encrypt?)
HOOKS=(base systemd sd-vconsole plymouth autodetect microcode modconf kms keyboard block filesystems sd-kmonad)

