alias open='xdg-open'
alias ll='ls -All -h'
alias vi='nvim'
alias vim='nvim'
alias pacinstall='doas pacman -S --needed'
alias uninstall='doas pacman -Runs'
alias pacupgrade='doas pacman -Sy && doas pacman -S --needed --noconfirm archlinux-keyring && doas pacman -Su'

alias dotgit='git --git-dir={$HOME}/.dotfiles/.git --work-tree={$HOME}'
alias sudo='sl -d10lFaw'
alias xprop='echo "This is sway, try: \"swaymsg -t get_tree\""'
alias m-usb='doas mount /home/bonsaiiv/usb'
alias u-usb='doas umount /home/bonsaiiv/usb'
alias hl='hledger --strict'
