#
# ~/.bashrc
#

if [ -f ~/.config/bash/bash_device ]; then
	. ~/.config/bash/bash_device
fi

if [ -f ~/.config/bash/bash_aliases ]; then
	. ~/.config/bash/bash_aliases
fi

alias ls='ls --color=auto'
alias grep='grep --color=auto'

export EDITOR='nvim'
export PYTHON_HISTORY='/home/bonsaiiv/.cache/python_history'
export _JAVA_AWT_WM_NONREPARENTING=1

PS1='\[\e[32m\]\u@\h\[\e[0m\]:\[\e[34m\]\W\[\e[0m\]\$ '

